# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build_and_sent_msg do

    gym(
      scheme: "one.lab.2.1-dev"
    )
  
    increment_build_number
    
    build_number = get_build_number

    telegram(
      message: "Success! Build: #{build_number}",
      chat_id: ""
      )
    end
end
