# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build_and_notify do
    # Build the project
    gym(
      project: "/Users/dsaiynov/Desktop/onelab-ios-ed/l2/one.lab.2.1 3/one.lab.2.1.xcodeproj",
      scheme: "Dev",
      clean: true,
      export_method: "development"
    )

    # Increment the build number
    increment_build_number(
      xcodeproj: "/Users/dsaiynov/Desktop/onelab-ios-ed/l2/one.lab.2.1 3/one.lab.2.1.xcodeproj"
    )

    # Get the version number
    version = get_version_number(
      xcodeproj: "/Users/dsaiynov/Desktop/onelab-ios-ed/l2/one.lab.2.1 3/one.lab.2.1.xcodeproj"
    )

    # Get the build number
    build_number = get_build_number(
      xcodeproj: "/Users/dsaiynov/Desktop/onelab-ios-ed/l2/one.lab.2.1 3/one.lab.2.1.xcodeproj"
    )

    # Compose the message
    message = "iOS build successful! Build number: #{build_number}, Bundle version: #{version}"

    # Send notification to Telegram
    telegram(
      text: message,
      chat_id: "1002076780677",
      token: "7186359908:AAE5Yf_x_BeXbGjYBtPaHXgwrIH7P0sDpME"
    )
  end
end

