# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :build_and_notify do
  gym(scheme: "Dev")

  increment_build_number
  increment_version_number

  version = get_version_number
  build_number = get_build_number

  telegram(
    message: "Успешно собрано приложение версии #{version} (билд #{build_number})"
  )
end

lane :tests do
  run_tests(scheme: "MyAppTests")
end
